# Generated by Django 6.0.2 on 2026-04-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estimator'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimator',
            name='customer_name',
            field=models.CharField(default='Customer', max_length=100),
        ),
    ]
