# Generated by Django 6.0.2 on 2026-04-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_estimator_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
