# Generated by Django 5.2.16 on 2026-07-27 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_estimator_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.estimator'),
        ),
    ]
